<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LastRegret.Tests</RootNamespace>
    <AssemblyName>LastRegret.Tests</AssemblyName>
    <UseWPF>false</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LastRegret.Core\LastRegret.Core.csproj" />
    <ProjectReference Include="..\..\src\LastRegret.Data\LastRegret.Data.csproj" />
    <ProjectReference Include="..\..\src\LastRegret.Engine\LastRegret.Engine.csproj" />
    <ProjectReference Include="..\..\src\LastRegret.Windows\LastRegret.Windows.csproj" />
    <ProjectReference Include="..\..\src\LastRegret.Runtime\LastRegret.Runtime.csproj" />
  </ItemGroup>

</Project>
